# Generated by Django 5.0.1 on 2024-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
