# Generated by Django 5.0.1 on 2024-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_servicemodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
