# Generated by Django 5.0.1 on 2024-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_servicemodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='comments_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='comments_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='comments_uz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes_uz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
