# Generated by Django 5.0.1 on 2024-01-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_blogmodel_comments_en_blogmodel_comments_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comments_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='comments_ru',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='comments_uz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes_ru',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes_uz',
        ),
    ]
