# Generated by Django 5.0.1 on 2024-01-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_blogmodel_comments_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='title_uz',
        ),
    ]
